force-app/main/default/objects/WebServiceConfiguration__mdt/WebServiceConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Contains the configurations necessary for web services callouts.</description>
    <label>WebServiceConfiguration</label>
    <pluralLabel>WebServiceConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/WebServiceConfiguration__mdt/fields/AppId__c.field-meta.xml
<CustomField>
    <fullName>AppId__c</fullName>
    <description>The app id for REddit integration.</description>
    <label>AppId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebServiceConfiguration__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The endpoint for the callout.</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebServiceConfiguration__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>The password to be used in the authentication.</description>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebServiceConfiguration__mdt/fields/Secret__c.field-meta.xml
<CustomField>
    <fullName>Secret__c</fullName>
    <description>THe secret to be used in the authentication.</description>
    <label>Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebServiceConfiguration__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>The username to be used in the authentication.</description>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RedditService.cls
public with sharing class RedditService {

    private static final String REDDIT_AUTH = 'RedditAuth';
    private static final String REDDIT_COMMENT = 'RedditComment';
    private static final String AUTH_ERROR = Label.AuthErrorMessage;
    private static final String COMMENT_ERROR = Label.RedditCommentError;
    private static final Integer SUCCESS_CODE = 200;

    private RedditService(){}

    /*
    * Posts a comment to Reddit.
    *
    * @param comment  the comment object
    */
    public static void postComment(RedditCommentDTO comment){
        
        WebServiceConfiguration__mdt serviceConfig = WebServiceConfiguration__mdt.getInstance(REDDIT_COMMENT);
        WebServiceConfiguration__mdt authConfig = WebServiceConfiguration__mdt.getInstance(REDDIT_AUTH);

        AuthDTO.Response token = getAuthToken(authConfig);

        HttpRequest request = new HttpRequest();
        request.setEndpoint(serviceConfig.Endpoint__c);
        request.setHeader('Authorization', 'Bearer ' + token.access_token);
        request.setHeader('User-Agent', authConfig.Username__c);
        request.setMethod('POST'); 
        request.setBody(JSON.serialize(comment));

        HttpResponse response = send(request);

        if(response.getStatusCode() != SUCCESS_CODE){
            throw new RedditException(COMMENT_ERROR.replace('{0}', String.valueOf(response.getStatusCode())));
        }        
    }

    /*
    * Performs the token retrieval using Basic Authentication.
    *
    * @param authconfig  the custom metadata with configuration details
    */
    private static AuthDTO.Response getAuthToken(WebServiceConfiguration__mdt authConfig){
        
        
        AuthDTO.Request authBody = new AuthDTO.Request();
        authBody.grant_type = 'password';
        authBody.username = authConfig.Username__c;
        authBody.password = authConfig.Password__c;

        HttpRequest request = new HttpRequest();
        request.setEndpoint(authConfig.Endpoint__c);
        request.setHeader('Authorization', getBasicAuthHeader(authConfig));
        request.setHeader('User-Agent', authConfig.Username__c);
        request.setMethod('POST'); 
        request.setBody(JSON.serialize(authBody));
               
        HttpResponse response = send(request);

        if(response.getStatusCode() != SUCCESS_CODE){
            throw new RedditException(AUTH_ERROR);
        }

        return (AuthDTO.Response) JSON.deserialize(response.getBody(), AuthDTO.Response.class);
    }

    private static String getBasicAuthHeader(WebServiceConfiguration__mdt config){

        Blob headerValue = Blob.valueOf(config.AppId__c + ':' + config.Secret__c);
        String authHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);

        return authHeader;
    }

    private static HttpResponse send(HttpRequest request){
        Http h = new Http();
        return h.send(request);
    }

    public class RedditException extends Exception{}
}